version: '3.4'

services:
  wms:
    image: wms
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 import_from_wms.py "]
    ports:
      - 5678:5678
